seed: 42
model_dir: ../../models/cfm_vc_f
resume_checkpoint: true

train:
  fp16: false
  batch_size: 32
  num_epochs: 5000
  save_interval: 100
  train_ratio: 0.9

data:
  data_dir: ./DATA

model:
  encoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    dropout: 0.1

  decoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    dropout: 0.1

optimizer:
  lr: 1.0
  betas: [0.9, 0.98]
