seed: 42
model_dir: ../../models/cfm_vc_gan
resume_checkpoint: false

train:
  fp16: false
  batch_size: 32
  num_epochs: 1000
  save_interval: 100
  train_ratio: 0.9

data:
  data_dir: ./DATA

model:
  n_mel: 80
  segment_length: 128

  encoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    kernel_size: 7
    dropout: 0.1

  decoder:
    channels: 384
    n_heads: 2
    n_layers: 4
    kernel_size: 7
    dropout: 0.1

  discriminator:
    channels: 384
    kernel_size: 5
    n_layers: 4

optimizer:
  lr: 1.0
  betas: [0.5, 0.99]
